### ISSUE TITLE
Question: Baud and Deviation

### ISSUE THREAD

**Issue by Crsarmv7l** [cdeletre/txtpms#3]
Hi, @cdeletre,

Thank you very much for your work on this project. I have been wanting to get into TPMS, and I enjoy seeing what is going on around me.

I got the baud and deviation for citroen (B: 19200 and D: 116,000), was wondering if you have the normal baud and deviation for Ford and Toyota.

**Comment by cdeletre** [comment]
Hi @Crsarmv7l 

Thank you for your feedback. It has been a long time I haven't played with TPMS sensors but looking back at the original rtl_433 source code I can see that the baudrate should be the same for citroen, ford and toyota implemented here. You can double check that the three device use the same number of samples for a pulse.

[Citroën](https://github.com/merbanan/rtl_433/blob/616b5d5eba341e589e733e12a87193383c54a7c5/src/devices/tpms_citroen.c#L138)
[Ford](https://github.com/merbanan/rtl_433/blob/616b5d5eba341e589e733e12a87193383c54a7c5/src/devices/tpms_ford.c#L230)
[Toyota](https://github.com/merbanan/rtl_433/blob/616b5d5eba341e589e733e12a87193383c54a7c5/src/devices/tpms_toyota.c#L120)

For the deviation I'm sorry but I have no idea but if I found something I'll post it here.

Have fun !

**Comment by Crsarmv7l** [comment]
Thank you

**Comment by cdeletre** [comment]
> Author

Hey! I got some flashbacks and I found the sample files repository I was playing with years ago (it's from the rtl_433 project)

Here is for the Ford TPMS:
https://github.com/merbanan/rtl_433_tests/tree/master/tests/Ford_TPMS

And for Toyota TPMS:
https://github.com/merbanan/rtl_433_tests/tree/master/tests/Toyota_TPMS

I guess these IQ records are 250 ksps but I haven't checked. You should be able to find the deviation by opening these files in inspectrum for example.

Enjoy ;)

**Comment by Crsarmv7l** [comment]
No luck getting ford or toyota generated files to work with rtl_433 as of yet, but I will keep at it. As an aside, had to change to this in all the tpms_(model).py in order to get them working

print(( 'manchester = %s' % str(manchester).replace('\xff','1').replace('\x00','_') ))

**Comment by Crsarmv7l** [comment]
Whelp, I spent a long time trying to solve a problem that was only kind of an issue. Rtl_433 ignores deviation. Its still not seeing my .cu8 files even with the buffer signal, but my end goal is a .sub file which when played back works fine.

Sorry, and thanks again.
